### ISSUE TITLE
Building on Linux/License Issue

### ISSUE THREAD

**Issue by heyzua** [stephenrkell/liballocs#5]
Hello,

I'm unable to get this to build on my Ubuntu x64 box. In particular, your dwarfpp project doesn't won't run `autoconf` without failing.

I'm also wondering whether you have a license for these, as I was thinking about using them to build a scheme/guile/racket library, presuming I can get it to build.

Thanks

**Comment by stephenrkell** [comment]
Hi, 

> I'm unable to get this to build on my Ubuntu x64 box. In particular,
> your dwarfpp project doesn't won't run `autoconf` without failing.
> 
> I'm also wondering whether you have a license for these, as I was
> thinking about using them to build a scheme/guile/racket library,
> presuming I can get it to build.

Thanks for these questions.

Can you give me a proper report of what goes wrong with autoconfing
libdwarfpp? The autoconfisation of these codebases is pretty new, and
I'm not yet using it myself. Feel free to open an issue on libdwarfpp.

I need to clean up these codebases later this week and merge some pull
requests. (Also there will be some ABI changes to liballocs.) So, I
might have to get back to you in a few days.

In the meantime, a slightly hacky alternative that might get you going
is the contrib/checkout.sh script in dwarfidl
<https://github.com/stephenrkell/dwarfidl/blob/master/contrib/checkout.sh>,
which will grab you most of the dependencies for liballocs. Read the
script first, since it states some assumptions about what's already on
your system... ANTLR v3.4 is the one you're most likely to lack.

About licensing: well done on being the first person to force this
question. (You'd also be the first external user.) I'm happy to license
it under LGPL v3, but if that doesn't work for you, come back to me and
we'll talk about alternatives.

I'd be intrigued to learn more about your Scheme library....

Stephen

**Comment by stephenrkell** [comment]
I've just overhauled the autoconf/automake in this repository and all my other repositories that it depends on. Please feel free to have another go and let me know how you get on. There is also now a README at the top-level documenting the various dependencies.

**Comment by stephenrkell** [comment]
I believe this now works, and I've also clarified the licensing situation... closing the ticket now, but further questions are most welcome of course.
